'use strict';

module.exports = [
  {
    method: 'POST',
    route: '/apps/:app/logs/query',
    upstream: '/apps/{app}/log-sessions',
    operationId: 'queryHerokuLogs',
    classification: 'read',
  },
  {
    method: 'PATCH',
    route: '/apps/:app/webhooks/:webhook',
    upstream: '/apps/{app}/webhooks/{webhook}',
    operationId: 'updateHerokuAppWebhook',
    classification: 'production-sensitive',
  },
  {
    method: 'GET',
    route: '/apps/:app/webhook-events',
    upstream: '/apps/{app}/webhook-events',
    operationId: 'listHerokuAppWebhookEvents',
    classification: 'read',
  },
  {
    method: 'GET',
    route: '/apps/:app/webhook-events/:event',
    upstream: '/apps/{app}/webhook-events/{event}',
    operationId: 'getHerokuAppWebhookEvent',
    classification: 'read',
  },
  {
    method: 'GET',
    route: '/app-transfers',
    upstream: '/account/app-transfers',
    operationId: 'listHerokuAppTransfers',
    classification: 'read',
  },
  {
    method: 'GET',
    route: '/app-transfers/:transfer',
    upstream: '/account/app-transfers/{transfer}',
    operationId: 'getHerokuAppTransfer',
    classification: 'read',
  },
  {
    method: 'PATCH',
    route: '/app-transfers/:transfer',
    upstream: '/account/app-transfers/{transfer}',
    operationId: 'updateHerokuAppTransfer',
    classification: 'access-admin',
  },
  {
    method: 'DELETE',
    route: '/app-transfers/:transfer',
    upstream: '/account/app-transfers/{transfer}',
    operationId: 'deleteHerokuAppTransfer',
    classification: 'destructive',
  },
  {
    method: 'GET',
    route: '/pipelines/:pipeline/review-app-config',
    upstream: '/pipelines/{pipeline}/review-app-config',
    operationId: 'getHerokuReviewAppConfig',
    classification: 'read',
  },
  {
    method: 'POST',
    route: '/pipelines/:pipeline/review-app-config',
    upstream: '/pipelines/{pipeline}/review-app-config',
    operationId: 'enableHerokuReviewAppConfig',
    classification: 'production-sensitive',
  },
  {
    method: 'PATCH',
    route: '/pipelines/:pipeline/review-app-config',
    upstream: '/pipelines/{pipeline}/review-app-config',
    operationId: 'updateHerokuReviewAppConfig',
    classification: 'production-sensitive',
  },
  {
    method: 'DELETE',
    route: '/pipelines/:pipeline/review-app-config',
    upstream: '/pipelines/{pipeline}/review-app-config',
    operationId: 'disableHerokuReviewAppConfig',
    classification: 'destructive',
  },
  {
    method: 'GET',
    route: '/pipelines/:pipeline/stack',
    upstream: '/pipelines/{pipeline}/pipeline-stack',
    operationId: 'getHerokuPipelineStack',
    classification: 'read',
  },
  {
    method: 'PATCH',
    route: '/pipelines/:pipeline/stack',
    upstream: '/pipelines/{pipeline}/pipeline-stack',
    operationId: 'updateHerokuPipelineStack',
    classification: 'production-sensitive',
  },
  {
    method: 'PATCH',
    route: '/spaces/:space/vpn-connections/:vpn',
    upstream: '/spaces/{space}/vpn-connections/{vpn}',
    operationId: 'updateHerokuSpaceVpnConnection',
    classification: 'private-space-admin',
  },
];
