'use strict';

const routes = [
  ['GET', '/account', '/account', 'getHerokuAccount', 'read'],
  ['PATCH', '/account', '/account', 'updateHerokuAccount', 'access-admin'],
  ['GET', '/account/rate-limits', '/account/rate-limits', 'getHerokuRateLimits', 'read'],
  ['GET', '/regions', '/regions', 'listHerokuRegions', 'read'],
  ['GET', '/regions/:region', '/regions/{region}', 'getHerokuRegion', 'read'],
  ['GET', '/stacks', '/stacks', 'listHerokuStacks', 'read'],
  ['GET', '/stacks/:stack', '/stacks/{stack}', 'getHerokuStack', 'read'],
  ['GET', '/apps', '/apps', 'listHerokuApps', 'read'],
  ['POST', '/apps', '/apps', 'createHerokuApp', 'billing-sensitive'],
  ['GET', '/apps/:app', '/apps/{app}', 'getHerokuApp', 'read'],
  ['PATCH', '/apps/:app', '/apps/{app}', 'updateHerokuApp', 'production-sensitive'],
  ['DELETE', '/apps/:app', '/apps/{app}', 'deleteHerokuApp', 'destructive'],
  ['POST', '/apps/:app/transfer', '/apps/{app}/transfer', 'transferHerokuApp', 'access-admin'],
  ['GET', '/apps/:app/features', '/apps/{app}/features', 'listHerokuAppFeatures', 'read'],
  [
    'GET',
    '/apps/:app/features/:feature',
    '/apps/{app}/features/{feature}',
    'getHerokuAppFeature',
    'read',
  ],
  [
    'PATCH',
    '/apps/:app/features/:feature',
    '/apps/{app}/features/{feature}',
    'updateHerokuAppFeature',
    'production-sensitive',
  ],
  [
    'GET',
    '/apps/:app/buildpacks',
    '/apps/{app}/buildpack-installations',
    'listHerokuBuildpacks',
    'read',
  ],
  [
    'POST',
    '/apps/:app/buildpacks',
    '/apps/{app}/buildpack-installations',
    'createHerokuBuildpack',
    'production-sensitive',
  ],
  [
    'PATCH',
    '/apps/:app/buildpacks/:position',
    '/apps/{app}/buildpack-installations/{position}',
    'updateHerokuBuildpack',
    'production-sensitive',
  ],
  [
    'DELETE',
    '/apps/:app/buildpacks/:position',
    '/apps/{app}/buildpack-installations/{position}',
    'deleteHerokuBuildpack',
    'destructive',
  ],
  ['GET', '/apps/:app/stack', '/apps/{app}/stack', 'getHerokuAppStack', 'read'],
  [
    'PATCH',
    '/apps/:app/stack',
    '/apps/{app}/stack',
    'updateHerokuAppStack',
    'production-sensitive',
  ],
  [
    'GET',
    '/apps/:app/config-vars',
    '/apps/{app}/config-vars',
    'listHerokuConfigVarMetadata',
    'read',
  ],
  [
    'PATCH',
    '/apps/:app/config-vars',
    '/apps/{app}/config-vars',
    'updateHerokuConfigVars',
    'production-sensitive',
  ],
  [
    'DELETE',
    '/apps/:app/config-vars/:key',
    '/apps/{app}/config-vars',
    'deleteHerokuConfigVar',
    'destructive',
  ],
  ['GET', '/apps/:app/dynos', '/apps/{app}/dynos', 'listHerokuDynos', 'read'],
  ['GET', '/apps/:app/dynos/:dyno', '/apps/{app}/dynos/{dyno}', 'getHerokuDyno', 'read'],
  [
    'DELETE',
    '/apps/:app/dynos/:dyno',
    '/apps/{app}/dynos/{dyno}',
    'stopHerokuDyno',
    'production-sensitive',
  ],
  [
    'DELETE',
    '/apps/:app/dynos',
    '/apps/{app}/dynos',
    'restartAllHerokuDynos',
    'production-sensitive',
  ],
  ['GET', '/apps/:app/formation', '/apps/{app}/formation', 'listHerokuFormation', 'read'],
  [
    'GET',
    '/apps/:app/formation/:type',
    '/apps/{app}/formation/{type}',
    'getHerokuFormation',
    'read',
  ],
  [
    'PATCH',
    '/apps/:app/formation',
    '/apps/{app}/formation',
    'batchUpdateHerokuFormation',
    'production-sensitive',
  ],
  [
    'PATCH',
    '/apps/:app/formation/:type',
    '/apps/{app}/formation/{type}',
    'updateHerokuFormation',
    'production-sensitive',
  ],
  ['POST', '/sources', '/sources', 'createHerokuSource', 'normal-write'],
  ['GET', '/apps/:app/builds', '/apps/{app}/builds', 'listHerokuBuilds', 'read'],
  ['POST', '/apps/:app/builds', '/apps/{app}/builds', 'createHerokuBuild', 'production-sensitive'],
  ['GET', '/apps/:app/builds/:build', '/apps/{app}/builds/{build}', 'getHerokuBuild', 'read'],
  ['GET', '/apps/:app/slugs', '/apps/{app}/slugs', 'listHerokuSlugs', 'read'],
  ['GET', '/apps/:app/slugs/:slug', '/apps/{app}/slugs/{slug}', 'getHerokuSlug', 'read'],
  ['POST', '/apps/:app/slugs', '/apps/{app}/slugs', 'createHerokuSlug', 'production-sensitive'],
  ['GET', '/apps/:app/releases', '/apps/{app}/releases', 'listHerokuReleases', 'read'],
  [
    'GET',
    '/apps/:app/releases/:release',
    '/apps/{app}/releases/{release}',
    'getHerokuRelease',
    'read',
  ],
  [
    'POST',
    '/apps/:app/releases',
    '/apps/{app}/releases',
    'createHerokuRelease',
    'production-sensitive',
  ],
  [
    'POST',
    '/apps/:app/releases/:release/rollback',
    '/apps/{app}/releases',
    'rollbackHerokuRelease',
    'production-sensitive',
  ],
  ['POST', '/apps/:app/log-sessions', '/apps/{app}/log-sessions', 'createHerokuLogSession', 'read'],
  ['GET', '/apps/:app/domains', '/apps/{app}/domains', 'listHerokuDomains', 'read'],
  [
    'POST',
    '/apps/:app/domains',
    '/apps/{app}/domains',
    'createHerokuDomain',
    'production-sensitive',
  ],
  ['GET', '/apps/:app/domains/:domain', '/apps/{app}/domains/{domain}', 'getHerokuDomain', 'read'],
  [
    'PATCH',
    '/apps/:app/domains/:domain',
    '/apps/{app}/domains/{domain}',
    'updateHerokuDomain',
    'production-sensitive',
  ],
  [
    'DELETE',
    '/apps/:app/domains/:domain',
    '/apps/{app}/domains/{domain}',
    'deleteHerokuDomain',
    'destructive',
  ],
  [
    'GET',
    '/apps/:app/sni-endpoints',
    '/apps/{app}/sni-endpoints',
    'listHerokuSniEndpoints',
    'read',
  ],
  [
    'GET',
    '/apps/:app/sni-endpoints/:endpoint',
    '/apps/{app}/sni-endpoints/{endpoint}',
    'getHerokuSniEndpoint',
    'read',
  ],
  [
    'POST',
    '/apps/:app/sni-endpoints',
    '/apps/{app}/sni-endpoints',
    'createHerokuSniEndpoint',
    'production-sensitive',
  ],
  [
    'PATCH',
    '/apps/:app/sni-endpoints/:endpoint',
    '/apps/{app}/sni-endpoints/{endpoint}',
    'updateHerokuSniEndpoint',
    'production-sensitive',
  ],
  [
    'DELETE',
    '/apps/:app/sni-endpoints/:endpoint',
    '/apps/{app}/sni-endpoints/{endpoint}',
    'deleteHerokuSniEndpoint',
    'destructive',
  ],
  ['GET', '/apps/:app/addons', '/apps/{app}/addons', 'listHerokuAddons', 'read'],
  ['POST', '/apps/:app/addons', '/apps/{app}/addons', 'createHerokuAddon', 'billing-sensitive'],
  ['GET', '/apps/:app/addons/:addon', '/apps/{app}/addons/{addon}', 'getHerokuAddon', 'read'],
  [
    'PATCH',
    '/apps/:app/addons/:addon',
    '/apps/{app}/addons/{addon}',
    'updateHerokuAddon',
    'billing-sensitive',
  ],
  [
    'DELETE',
    '/apps/:app/addons/:addon',
    '/apps/{app}/addons/{addon}',
    'deleteHerokuAddon',
    'destructive',
  ],
  [
    'GET',
    '/apps/:app/addon-attachments',
    '/apps/{app}/addon-attachments',
    'listHerokuAddonAttachments',
    'read',
  ],
  [
    'POST',
    '/apps/:app/addon-attachments',
    '/apps/{app}/addon-attachments',
    'createHerokuAddonAttachment',
    'production-sensitive',
  ],
  [
    'GET',
    '/apps/:app/addon-attachments/:attachment',
    '/apps/{app}/addon-attachments/{attachment}',
    'getHerokuAddonAttachment',
    'read',
  ],
  [
    'PATCH',
    '/apps/:app/addon-attachments/:attachment',
    '/apps/{app}/addon-attachments/{attachment}',
    'updateHerokuAddonAttachment',
    'production-sensitive',
  ],
  [
    'DELETE',
    '/apps/:app/addon-attachments/:attachment',
    '/apps/{app}/addon-attachments/{attachment}',
    'deleteHerokuAddonAttachment',
    'destructive',
  ],
  [
    'GET',
    '/apps/:app/collaborators',
    '/apps/{app}/collaborators',
    'listHerokuCollaborators',
    'read',
  ],
  [
    'POST',
    '/apps/:app/collaborators',
    '/apps/{app}/collaborators',
    'createHerokuCollaborator',
    'access-admin',
  ],
  [
    'GET',
    '/apps/:app/collaborators/:collaborator',
    '/apps/{app}/collaborators/{collaborator}',
    'getHerokuCollaborator',
    'read',
  ],
  [
    'PATCH',
    '/apps/:app/collaborators/:collaborator',
    '/apps/{app}/collaborators/{collaborator}',
    'updateHerokuCollaborator',
    'access-admin',
  ],
  [
    'DELETE',
    '/apps/:app/collaborators/:collaborator',
    '/apps/{app}/collaborators/{collaborator}',
    'deleteHerokuCollaborator',
    'access-admin',
  ],
  ['GET', '/pipelines', '/pipelines', 'listHerokuPipelines', 'read'],
  ['POST', '/pipelines', '/pipelines', 'createHerokuPipeline', 'normal-write'],
  ['GET', '/pipelines/:pipeline', '/pipelines/{pipeline}', 'getHerokuPipeline', 'read'],
  [
    'PATCH',
    '/pipelines/:pipeline',
    '/pipelines/{pipeline}',
    'updateHerokuPipeline',
    'production-sensitive',
  ],
  [
    'DELETE',
    '/pipelines/:pipeline',
    '/pipelines/{pipeline}',
    'deleteHerokuPipeline',
    'destructive',
  ],
  [
    'GET',
    '/pipelines/:pipeline/apps',
    '/pipelines/{pipeline}/pipeline-couplings',
    'listHerokuPipelineApps',
    'read',
  ],
  [
    'POST',
    '/pipelines/:pipeline/apps',
    '/pipeline-couplings',
    'createHerokuPipelineCoupling',
    'production-sensitive',
  ],
  [
    'DELETE',
    '/pipelines/:pipeline/apps/:coupling',
    '/pipeline-couplings/{coupling}',
    'deleteHerokuPipelineCoupling',
    'destructive',
  ],
  [
    'POST',
    '/pipelines/:pipeline/promotions',
    '/pipeline-promotions',
    'createHerokuPipelinePromotion',
    'production-sensitive',
  ],
  [
    'GET',
    '/pipeline-promotions/:promotion',
    '/pipeline-promotions/{promotion}',
    'getHerokuPipelinePromotion',
    'read',
  ],
  [
    'GET',
    '/pipeline-promotions/:promotion/targets',
    '/pipeline-promotions/{promotion}/pipeline-promotion-targets',
    'listHerokuPipelinePromotionTargets',
    'read',
  ],
  [
    'GET',
    '/pipelines/:pipeline/stages/:stage/config-vars',
    '/pipelines/{pipeline}/stage/{stage}/config-vars',
    'listHerokuPipelineConfigVarMetadata',
    'read',
  ],
  [
    'PATCH',
    '/pipelines/:pipeline/stages/:stage/config-vars',
    '/pipelines/{pipeline}/stage/{stage}/config-vars',
    'updateHerokuPipelineConfigVars',
    'production-sensitive',
  ],
  [
    'GET',
    '/pipelines/:pipeline/review-apps',
    '/pipelines/{pipeline}/review-apps',
    'listHerokuReviewApps',
    'read',
  ],
  [
    'POST',
    '/pipelines/:pipeline/review-apps',
    '/review-apps',
    'createHerokuReviewApp',
    'billing-sensitive',
  ],
  ['GET', '/review-apps/:reviewApp', '/review-apps/{reviewApp}', 'getHerokuReviewApp', 'read'],
  [
    'DELETE',
    '/review-apps/:reviewApp',
    '/review-apps/{reviewApp}',
    'deleteHerokuReviewApp',
    'destructive',
  ],
  ['GET', '/apps/:app/webhooks', '/apps/{app}/webhooks', 'listHerokuAppWebhooks', 'read'],
  [
    'POST',
    '/apps/:app/webhooks',
    '/apps/{app}/webhooks',
    'createHerokuAppWebhook',
    'production-sensitive',
  ],
  [
    'GET',
    '/apps/:app/webhooks/:webhook',
    '/apps/{app}/webhooks/{webhook}',
    'getHerokuAppWebhook',
    'read',
  ],
  [
    'DELETE',
    '/apps/:app/webhooks/:webhook',
    '/apps/{app}/webhooks/{webhook}',
    'deleteHerokuAppWebhook',
    'destructive',
  ],
  [
    'GET',
    '/apps/:app/webhook-deliveries',
    '/apps/{app}/webhook-deliveries',
    'listHerokuAppWebhookDeliveries',
    'read',
  ],
  [
    'GET',
    '/apps/:app/webhook-deliveries/:delivery',
    '/apps/{app}/webhook-deliveries/{delivery}',
    'getHerokuAppWebhookDelivery',
    'read',
  ],
  ['GET', '/teams', '/teams', 'listHerokuTeams', 'read'],
  ['POST', '/teams', '/teams', 'createHerokuTeam', 'billing-sensitive'],
  ['GET', '/teams/:team', '/teams/{team}', 'getHerokuTeam', 'read'],
  ['PATCH', '/teams/:team', '/teams/{team}', 'updateHerokuTeam', 'access-admin'],
  ['DELETE', '/teams/:team', '/teams/{team}', 'deleteHerokuTeam', 'destructive'],
  ['GET', '/teams/:team/apps', '/teams/{team}/apps', 'listHerokuTeamApps', 'read'],
  ['GET', '/teams/:team/members', '/teams/{team}/members', 'listHerokuTeamMembers', 'read'],
  [
    'POST',
    '/teams/:team/members',
    '/teams/{team}/members',
    'createHerokuTeamMember',
    'access-admin',
  ],
  [
    'PATCH',
    '/teams/:team/members/:member',
    '/teams/{team}/members/{member}',
    'updateHerokuTeamMember',
    'access-admin',
  ],
  [
    'DELETE',
    '/teams/:team/members/:member',
    '/teams/{team}/members/{member}',
    'deleteHerokuTeamMember',
    'access-admin',
  ],
  [
    'GET',
    '/teams/:team/invitations',
    '/teams/{team}/invitations',
    'listHerokuTeamInvitations',
    'read',
  ],
  [
    'POST',
    '/teams/:team/invitations',
    '/teams/{team}/invitations',
    'createHerokuTeamInvitation',
    'access-admin',
  ],
  [
    'DELETE',
    '/teams/:team/invitations/:invitation',
    '/teams/{team}/invitations/{invitation}',
    'deleteHerokuTeamInvitation',
    'access-admin',
  ],
  [
    'GET',
    '/teams/:team/usage/daily',
    '/teams/{team}/usage/daily',
    'getHerokuTeamDailyUsage',
    'read',
  ],
  [
    'GET',
    '/teams/:team/usage/monthly',
    '/teams/{team}/usage/monthly',
    'getHerokuTeamMonthlyUsage',
    'read',
  ],
  ['GET', '/teams/:team/invoices', '/teams/{team}/invoices', 'listHerokuTeamInvoices', 'read'],
  ['GET', '/spaces', '/spaces', 'listHerokuSpaces', 'read'],
  ['POST', '/spaces', '/spaces', 'createHerokuSpace', 'private-space-admin'],
  ['GET', '/spaces/:space', '/spaces/{space}', 'getHerokuSpace', 'read'],
  ['PATCH', '/spaces/:space', '/spaces/{space}', 'updateHerokuSpace', 'private-space-admin'],
  ['DELETE', '/spaces/:space', '/spaces/{space}', 'deleteHerokuSpace', 'destructive'],
  ['GET', '/spaces/:space/apps', '/spaces/{space}/apps', 'listHerokuSpaceApps', 'read'],
  [
    'GET',
    '/spaces/:space/access',
    '/spaces/{space}/space-accesses',
    'listHerokuSpaceAccess',
    'read',
  ],
  [
    'POST',
    '/spaces/:space/access',
    '/spaces/{space}/space-accesses',
    'createHerokuSpaceAccess',
    'private-space-admin',
  ],
  [
    'DELETE',
    '/spaces/:space/access/:member',
    '/spaces/{space}/space-accesses/{member}',
    'deleteHerokuSpaceAccess',
    'private-space-admin',
  ],
  ['GET', '/spaces/:space/topology', '/spaces/{space}/topology', 'getHerokuSpaceTopology', 'read'],
  ['GET', '/spaces/:space/nat', '/spaces/{space}/nat', 'getHerokuSpaceNat', 'read'],
  [
    'GET',
    '/spaces/:space/vpn-connections',
    '/spaces/{space}/vpn-connections',
    'listHerokuSpaceVpnConnections',
    'read',
  ],
  [
    'POST',
    '/spaces/:space/vpn-connections',
    '/spaces/{space}/vpn-connections',
    'createHerokuSpaceVpnConnection',
    'private-space-admin',
  ],
  [
    'GET',
    '/spaces/:space/vpn-connections/:vpn',
    '/spaces/{space}/vpn-connections/{vpn}',
    'getHerokuSpaceVpnConnection',
    'read',
  ],
  [
    'DELETE',
    '/spaces/:space/vpn-connections/:vpn',
    '/spaces/{space}/vpn-connections/{vpn}',
    'deleteHerokuSpaceVpnConnection',
    'destructive',
  ],
].map(([method, route, upstream, operationId, classification]) => ({
  method,
  route,
  upstream,
  operationId,
  classification,
}));

module.exports = routes;
